language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- pypy
- pypy3
- '2.7'
- '3.4'
- '3.5'
- '3.6'
matrix:
  fast_finish: true
  include:
  - python: '3.7'
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
install:
- travis_retry pip install tox-travis
- travis_retry pip install coveralls
- travis_retry pip install coverage
script:
  tox
after_success:
- coveralls
